### ISSUE TITLE
Android System Webview fails to function on version v4-0.9.0-264 to v4-0.9.3-283

### ISSUE THREAD

**Issue by tinbilly** [Yervant7/ZygiskNext#5]
### Steps to reproduce/复现步骤

Scenario 1
1. Go to microG Settings
2. Click Account (Add Google account)
3. Click Sign In

OR

Scenario 2
1. Go to Inbox (mine is com.blackberry.hub)
2.  Click on any email

### Expected behaviour/预期行为

Scenario 1: The Google Sign in should display

Scenario 2: The email content should display

### Actual behaviour/实际行为

Scenario 1: Just the loading screen appears

Scenario 2: Just the loading screen appears

### KernelSU Module List/KernelSU 模块列表

```Shell
- microG Installer Revived v.3.4.2-0
- Zygisk Next for APatch
```

### Zygisk Next version/Zygisk Next 版本

v4-0.9.0-264 and later

### Android version/Android 版本

crdroid v7.19 (A11)

### KernelSU version/KernelSU 版本

Kernel Version: 4.14.202-perf+

### Version requirement/版本要求

- [ ] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

n/a

**Comment by Yervant7** [comment]
Try disabling exclude for the webview in APatch

**Comment by tinbilly** [comment]
Many thanks. No same issue on v4-0.9.3-285. Btw, I do not have to disable exclude for the webview in APatch.

**Comment by tinbilly** [comment]
Thanks for your work.

**Comment by inmaldrerah** [comment]
This thing seems to be related to system/product/overlay/microGOverlay/microGOverlay.apk in the microG module. removing this file and repacking makes it work in these versions. I don't know the actual reason though. It seems this overlay cannot work with the unmounting mechanism.
