### ISSUE TITLE
Support Tango Translator

### ISSUE THREAD

**Issue by a7365fbe** [Yervant7/ZygiskNext#8]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

The Snapdragon 8G3 has completely removed 32-bit support, but the Mi 14 series uses Tango Translator to run 32-bit apps, and although the official zygisknext version has 32-bit support, it doesn't support Tango Translator, and it doesn't work on an app translated through Tango Translator

### Describe the solution you'd like/描述你想要的解决方案

Enables zygisknext to function properly on the 32-bit app translated via Tango Translator

### Additional context/其他信息

@

**Comment by Memory2314** [comment]
The official version has been able to support it.

**Comment by a7365fbe** [comment]
https://github.com/Dr-TSNG/ZygiskNext/releases/tag/v4-0.9.2
